name: "Changelog generator"
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Conventional Changelog test Action
        uses: TriPSs/conventional-changelog-action@v5.2.0
        with:
          github-token: ${{ secrets.github_token }}
